### ISSUE TITLE
Add transparent background option

### ISSUE THREAD

**Issue by CRAG666** [FrenzyExists/aquarium-vim#1]
I really like my screen background, I would like to have the option of transparent background

**Comment by FrenzyExists** [comment]
Sup! Sorry for the late response, college stuff.

The background its something that the compositor would do, like picom or wayfire, not the theme perse.

**Comment by CRAG666** [comment]
I was wrong, it is the background color of my terminal

**Comment by CRAG666** [comment]
I was thinking of something like g:aquarium_transparent_background

**Comment by FrenzyExists** [comment]
Yeah but, that's done by the compositor, not the terminal nor the colorscheme

**Comment by FrenzyExists** [comment]
Btw, I noticed you're a spanish speaker, since I'm also a spanish speaker I'll speak spanish too, spanish is much better.

Osea aquarium-vim ni ninguna paleta de colores (que tenga entendido) tiene una opcion para transparencia porque la transparencia no se controla por ahí. Se controla por el compositor, que por medio de un window class o algo así puede cambiar la opacidad de la ventana. Como lo que hace picom. Para DEs como KDE o Ubuntu, creo que se hace por un programa que tienen incorporado, se que KDE tenia un compositor y que por Konsole o por el terminal de Ubuntu podias cambiar la opacidad, osea en los settings del terminal.

**Comment by CRAG666** [comment]
hola si hablo español como segundo idioma, quizás no he sabido como expresarme, la mayoría de esquemas de colores tienen la opción que menciono, te dejare un ejemplo para que sepas de que hablo, https://github.com/franbach/miramare#configuration, checa la primera opción es a lo que me refiero, por cierto me encanta tu esquema de color

**Comment by FrenzyExists** [comment]
Hola!

Le di una mirada al codigo de miramare y ahí sí pude entender lo que querías decir sobre la transparencia:

![image](https://user-images.githubusercontent.com/47986470/138576566-d58ee511-efc4-4416-b4f1-37fb7735a20a.png)

Este snippet de miramare lo que hace es que quita el background color del gui-vim, la cual daria ese efecto de transparencia que estabas mencionando. Ahorita lo implemento a aquarium :+1:

**Comment by FrenzyExists** [comment]
Done :D 206dd24627e8274abc2978e5c2dfc5f3ea12689a
Now aquarium supports transparency!
@CRAG666 ¡Muchisimas gracias por el issue, disculpa si no pude entender bien al princio jaja! 😅
